/* eslint-disable no-console */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { TICKERS } from '@/constants/tickers';
import { buildDataset, splitByDate, type Sample } from '@/services/predictor/dataset';
import { evaluate } from '@/services/predictor/evaluate';
import { FEATURE_NAMES } from '@/services/predictor/features';
import { predictProba, trainBatch, type Model } from '@/services/predictor/model';
import { HORIZON_DAYS, PREDICTOR_L2 } from '@/services/predictor/config';

import { loadBars, TRAINING_UNIVERSE } from './fetch-bars.ts';

// Offline verification and weight generation for the predictor.
//
// Trains only on history older than a holdout window, scores the untouched
// recent window, and writes the resulting weights to
// services/predictor/pretrained.ts. Every accuracy claim the app makes
// traces back to a number printed here, against real market data.
//
//   npm run eval:predictor            # 10-month holdout (default)
//   HOLDOUT_MONTHS=24 npm run eval:predictor
//   REFRESH=1 npm run eval:predictor  # refetch from Yahoo

const HOLDOUT_MONTHS = Number(process.env.HOLDOUT_MONTHS ?? 10);
const OUT_PATH = join(process.cwd(), 'services', 'predictor', 'pretrained.ts');
const SELFTEST_PATH = join(process.cwd(), 'services', 'predictor', 'selfTestSet.ts');

// Everything before this date is withheld from training entirely and frozen
// into the app as a self-test set (services/predictor/selfTestSet.ts). It is
// 7-10 years old, spans a different market regime, and the shipped weights
// have never seen it — so if on-device online learning ever drifts into
// nonsense, scoring this set catches it.
const SELFTEST_ERA_END = '2019-01-01';
const SELFTEST_SAMPLE_COUNT = 400;

function pct(v: number): string {
  return `${(v * 100).toFixed(2)}%`;
}

/** "Buy what went up" — the naive rule the old heuristic effectively used. */
function momentumBaseline(samples: Sample[]): number {
  const idx = FEATURE_NAMES.indexOf('ret5');
  let correct = 0;
  for (const s of samples) if ((s.x[idx] > 0 ? 1 : 0) === s.y) correct += 1;
  return correct / Math.max(1, samples.length);
}

/**
 * The operating decision that matters: how sure must the model be before it
 * says anything at all? Everything below the threshold is reported to the
 * user as "no clear signal" rather than a coin-flip dressed up as a call.
 */
function thresholdTable(model: Model, samples: Sample[]) {
  console.log('\n=== ABSTAIN THRESHOLD (how selective should a call be?) ===');
  console.log('threshold  coverage   accuracy   baseline   edge');
  for (const t of [0.5, 0.52, 0.54, 0.56, 0.58, 0.6, 0.62]) {
    let total = 0;
    let correct = 0;
    let positives = 0;
    for (const s of samples) {
      const p = predictProba(model, s.x);
      if (p < t && p > 1 - t) continue;
      total += 1;
      if ((p >= 0.5 ? 1 : 0) === s.y) correct += 1;
      if (s.y === 1) positives += 1;
    }
    if (total < 30) continue;
    const acc = correct / total;
    const base = Math.max(positives / total, 1 - positives / total);
    console.log(
      `  ${t.toFixed(2)}     ${pct(total / samples.length).padStart(7)}   ${pct(acc).padStart(7)}   ` +
        `${pct(base).padStart(7)}   ${acc - base >= 0 ? '+' : ''}${((acc - base) * 100).toFixed(2)} pts`
    );
  }
}

function writeWeights(model: Model, metrics: ReturnType<typeof evaluate>, meta: Record<string, unknown>) {
  const body = `// GENERATED by scripts/evaluate-predictor.ts — do not edit by hand.
//
// Weights fitted over ${meta.trainSamples} pooled samples from ${meta.universeSize} US large caps
// (${meta.firstDate} to ${meta.trainEnd}), then measured against a ${meta.holdoutMonths}-month
// holdout the fit never saw (${meta.testSamples} samples, ${meta.testStart} to ${meta.testEnd}).
//
// Measured out-of-sample: AUC ${metrics.auc.toFixed(4)}, accuracy ${pct(metrics.accuracy)}
// vs a ${pct(metrics.baselineAccuracy)} always-majority baseline. On calls it is
// confident enough to actually make, accuracy was ${pct(metrics.highConfidence.accuracy)} over
// ${pct(metrics.highConfidence.coverage)} of samples. Regenerate with: npm run eval:predictor
import type { Model } from '@/services/predictor/model';

export const PRETRAINED: Model = ${JSON.stringify(
    {
      version: model.version,
      weights: model.weights.map((w) => Number(w.toFixed(6))),
      bias: Number(model.bias.toFixed(6)),
      mean: model.mean.map((m) => Number(m.toFixed(8))),
      std: model.std.map((s) => Number(s.toFixed(8))),
      samples: model.samples,
      trainedAt: 0,
    },
    null,
    2
  )};

/** Out-of-sample measurements for the weights above, shown in the app. */
export const PRETRAINED_METRICS = {
  auc: ${metrics.auc.toFixed(4)},
  accuracy: ${metrics.accuracy.toFixed(4)},
  baselineAccuracy: ${metrics.baselineAccuracy.toFixed(4)},
  confidentAccuracy: ${metrics.highConfidence.accuracy.toFixed(4)},
  confidentCoverage: ${metrics.highConfidence.coverage.toFixed(4)},
  testSamples: ${metrics.samples},
  holdoutMonths: ${meta.holdoutMonths},
};
`;
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, body);
  console.log(`\nWrote weights -> ${OUT_PATH}`);
}

function writeSelfTestSet(frozen: Sample[], metrics: ReturnType<typeof evaluate>) {
  const rows = frozen.map((s) => ({
    x: s.x.map((v) => Number(v.toFixed(6))),
    y: s.y,
  }));
  const body = `// GENERATED by scripts/evaluate-predictor.ts — do not edit by hand.
//
// A frozen slice of market history from ${frozen[0].date} to ${frozen[frozen.length - 1].date} —
// ${frozen.length} samples the shipped weights were never trained on, spanning a
// different market regime than the training window.
//
// The app scores this set on every launch. The point isn't to re-verify the
// shipped weights (those are fixed and already measured); it's that on-device
// online learning MUTATES those weights over time, and a bad run of outcomes
// could in principle drag them somewhere useless. This is the tripwire: if
// accuracy on known history collapses, the app stops showing predictions
// instead of quietly serving corrupted ones.
export const SELF_TEST_SET: { x: number[]; y: number }[] = ${JSON.stringify(rows)};

/** What the shipped weights scored here at build time. */
export const SELF_TEST_BASELINE = {
  accuracy: ${metrics.accuracy.toFixed(4)},
  auc: ${metrics.auc.toFixed(4)},
  samples: ${frozen.length},
  eraStart: '${frozen[0].date}',
  eraEnd: '${frozen[frozen.length - 1].date}',
};
`;
  writeFileSync(SELFTEST_PATH, body);
  console.log(`Wrote self-test set -> ${SELFTEST_PATH}`);
}

async function main() {
  const barsBySymbol = await loadBars(TRAINING_UNIVERSE, 'training-universe');
  if (barsBySymbol.size === 0) {
    console.error('No data fetched — cannot evaluate.');
    process.exit(1);
  }

  const samples = buildDataset(barsBySymbol, { horizon: HORIZON_DAYS, labelMode: 'absolute' });
  const firstDate = samples[0].date;
  const lastDate = samples[samples.length - 1].date;
  console.log(`Dataset: ${samples.length} samples from ${barsBySymbol.size} symbols, ${firstDate} -> ${lastDate}`);
  console.log(`Target: close ${HORIZON_DAYS} sessions ahead is higher than today\n`);

  const cutoff = new Date(lastDate);
  cutoff.setMonth(cutoff.getMonth() - HOLDOUT_MONTHS);
  const cutoffDate = cutoff.toISOString().slice(0, 10);

  // Three-way split. The early era is carved out first so it never touches
  // training, then the usual recent holdout is taken off the end.
  const selfTestEra = samples.filter((s) => s.date < SELFTEST_ERA_END);
  const modern = samples.filter((s) => s.date >= SELFTEST_ERA_END);
  const { train, test } = splitByDate(modern, cutoffDate, HORIZON_DAYS);
  console.log(`Self-test era  ${selfTestEra.length} samples before ${SELFTEST_ERA_END} (never trained on)`);
  console.log(`Split at ${cutoffDate} (${HOLDOUT_MONTHS}-month holdout)`);
  console.log(`  train ${train.length} samples through ${train[train.length - 1].date}`);
  console.log(`  test  ${test.length} samples ${test[0].date} -> ${lastDate}\n`);

  console.time('train');
  const model = trainBatch(
    train.map((s) => s.x),
    train.map((s) => s.y),
    { l2: PREDICTOR_L2, iterations: 500 }
  );
  console.timeEnd('train');

  const inSample = evaluate(model, train);
  const out = evaluate(model, test);

  console.log('\n=== OUT OF SAMPLE (the number that counts) ===');
  console.log(`samples                    ${out.samples}`);
  console.log(`accuracy                   ${pct(out.accuracy)}`);
  console.log(`always-majority baseline   ${pct(out.baselineAccuracy)}`);
  console.log(`naive momentum baseline    ${pct(momentumBaseline(test))}`);
  console.log(`AUC                        ${out.auc.toFixed(4)}   (0.50 = coin flip)`);
  console.log(`Brier                      ${out.brier.toFixed(4)}   (lower better)`);
  console.log(`log loss                   ${out.logLoss.toFixed(4)}`);

  thresholdTable(model, test);

  console.log('\ncalibration (predicted vs actual):');
  for (const b of out.calibration) {
    if (b.count < 50) continue;
    console.log(
      `  ${b.bucket.padEnd(9)} n=${String(b.count).padStart(6)}  predicted ${pct(b.predicted)}  actual ${pct(b.actual)}`
    );
  }

  console.log('\n=== OVERFIT CHECK ===');
  console.log(`in-sample AUC ${inSample.auc.toFixed(4)} vs out-of-sample ${out.auc.toFixed(4)}`);
  const gap = inSample.auc - out.auc;
  console.log(`gap ${gap.toFixed(4)} ${gap > 0.05 ? '<- OVERFITTING' : '<- healthy'}`);

  console.log('\n=== PER-YEAR (is the edge stable or one lucky regime?) ===');
  const byYear = new Map<string, Sample[]>();
  for (const s of samples) {
    const y = s.date.slice(0, 4);
    if (!byYear.has(y)) byYear.set(y, []);
    byYear.get(y)!.push(s);
  }
  for (const [year, rows] of [...byYear.entries()].sort()) {
    if (rows.length < 500) continue;
    const m = evaluate(model, rows);
    const held = year >= cutoffDate.slice(0, 4) ? '  (holdout)' : '';
    console.log(
      `  ${year}  n=${String(rows.length).padStart(6)}  acc ${pct(m.accuracy)}  base ${pct(
        m.baselineAccuracy
      )}  AUC ${m.auc.toFixed(3)}${held}`
    );
  }

  console.log('\n=== FEATURE WEIGHTS (standardised) ===');
  const ranked = model.weights
    .map((w, i) => ({ name: FEATURE_NAMES[i], w }))
    .sort((a, b) => Math.abs(b.w) - Math.abs(a.w));
  for (const f of ranked) {
    console.log(
      `  ${f.name.padEnd(15)} ${f.w >= 0 ? '+' : '-'}${Math.abs(f.w).toFixed(4)} ${'#'.repeat(
        Math.min(40, Math.round(Math.abs(f.w) * 300))
      )}`
    );
  }

  console.log('\n=== SIGNAL CHECK (mean forward return by predicted decile) ===');
  const scored = test.map((s) => ({ p: predictProba(model, s.x), r: s.forwardReturn })).sort((a, b) => a.p - b.p);
  const size = Math.floor(scored.length / 10);
  if (size > 0) {
    for (let d = 0; d < 10; d++) {
      const slice = scored.slice(d * size, (d + 1) * size);
      console.log(
        `  decile ${String(d + 1).padStart(2)}  mean fwd ${HORIZON_DAYS}d return ${pct(
          slice.reduce((s, x) => s + x.r, 0) / slice.length
        )}`
      );
    }
    const bottom = scored.slice(0, size).reduce((s, x) => s + x.r, 0) / size;
    const top = scored.slice(-size).reduce((s, x) => s + x.r, 0) / size;
    console.log(`  top-minus-bottom spread ${pct(top - bottom)}`);
  }

  // Sanity: the app's own 27 tickers are a subset of the training universe,
  // so confirm the edge holds on exactly the names users will see.
  const appSymbols = new Set(TICKERS.map((t) => t.symbol));
  const appTest = test.filter((s) => appSymbols.has(s.symbol));
  if (appTest.length > 100) {
    const m = evaluate(model, appTest);
    console.log(`\n=== ON THE APP'S ${appSymbols.size} TICKERS ONLY ===`);
    console.log(
      `  n=${m.samples}  acc ${pct(m.accuracy)}  base ${pct(m.baselineAccuracy)}  AUC ${m.auc.toFixed(
        4
      )}  confident ${pct(m.highConfidence.accuracy)} over ${pct(m.highConfidence.coverage)}`
    );
  }

  // Freeze an evenly-spread slice of the untouched early era into the app.
  const selfTestMetrics = evaluate(model, selfTestEra);
  console.log('\n=== SELF-TEST ERA (7-10 years old, never trained on) ===');
  console.log(
    `  n=${selfTestMetrics.samples}  acc ${pct(selfTestMetrics.accuracy)}  base ${pct(
      selfTestMetrics.baselineAccuracy
    )}  AUC ${selfTestMetrics.auc.toFixed(4)}`
  );

  const step = Math.max(1, Math.floor(selfTestEra.length / SELFTEST_SAMPLE_COUNT));
  const frozen = selfTestEra.filter((_, i) => i % step === 0).slice(0, SELFTEST_SAMPLE_COUNT);
  const frozenMetrics = evaluate(model, frozen);
  console.log(
    `  frozen subset n=${frozen.length}  acc ${pct(frozenMetrics.accuracy)}  AUC ${frozenMetrics.auc.toFixed(4)}`
  );
  writeSelfTestSet(frozen, frozenMetrics);

  writeWeights(model, out, {
    trainSamples: train.length,
    testSamples: test.length,
    universeSize: barsBySymbol.size,
    firstDate,
    trainEnd: train[train.length - 1].date,
    testStart: test[0].date,
    testEnd: lastDate,
    holdoutMonths: HOLDOUT_MONTHS,
  });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
