// GENERATED by scripts/evaluate-predictor.ts — do not edit by hand.
//
// Weights fitted over 150223 pooled samples from 90 US large caps
// (2017-09-14 to 2025-08-27), then measured against a 10-month
// holdout the fit never saw (18900 samples, 2025-10-07 to 2026-08-07).
//
// Measured out-of-sample: AUC 0.5116, accuracy 53.84%
// vs a 53.95% always-majority baseline. On calls it is
// confident enough to actually make, accuracy was 55.19% over
// 14.52% of samples. Regenerate with: npm run eval:predictor
import type { Model } from '@/services/predictor/model';

export const PRETRAINED: Model = {
  "version": 1,
  "weights": [
    -0.013766,
    -0.016478,
    0.014957,
    -0.005964,
    -0.011122,
    -0.022188,
    -0.003246,
    -0.004027,
    0.035929,
    0.011985,
    0.007758,
    -0.024774,
    0.005717,
    -0.052221,
    -0.029002,
    -0.08254,
    -0.040637,
    0.04604,
    0.028327,
    0.025693,
    0.013019,
    0.042511,
    0.025723,
    -0.04923,
    -0.020611,
    0.078082,
    0.150143,
    -0.126
  ],
  "bias": 0.277274,
  "mean": [
    0.00068302,
    0.0033953,
    0.00670331,
    0.0128899,
    0.0358234,
    0.00369547,
    0.00647136,
    0.01210553,
    0.05762082,
    0.00006235,
    0.18226577,
    0.01798034,
    -0.06980678,
    0.02287516,
    0.09464674,
    -0.07509106,
    0.02139253,
    0.00036924,
    0.00002326,
    0.13398151,
    -0.13002952,
    0.23328832,
    0.00012057,
    0.01299746,
    0.03619081,
    0.05300261,
    0.01032318,
    -0.04411519
  ],
  "std": [
    0.02073944,
    0.04472188,
    0.06250598,
    0.08890143,
    0.15063729,
    0.03841784,
    0.04756591,
    0.07721321,
    0.34134409,
    0.00831611,
    1.29917383,
    0.0105631,
    0.37262928,
    0.01204681,
    0.52762361,
    0.07858791,
    0.10952933,
    0.00578376,
    0.07305262,
    0.37434227,
    0.12319575,
    1.03513918,
    0.13007935,
    0.05110383,
    0.07633894,
    0.06991561,
    0.00747904,
    0.05357888
  ],
  "samples": 150223,
  "trainedAt": 0
};

/** Out-of-sample measurements for the weights above, shown in the app. */
export const PRETRAINED_METRICS = {
  auc: 0.5116,
  accuracy: 0.5384,
  baselineAccuracy: 0.5395,
  confidentAccuracy: 0.5519,
  confidentCoverage: 0.1452,
  testSamples: 18900,
  holdoutMonths: 10,
};
