// GENERATED by scripts/evaluate-predictor.ts — do not edit by hand.
//
// Weights fitted over 152293 pooled samples from 90 US large caps
// (2017-09-14 to 2025-09-30), then measured against a 10-month
// holdout the fit never saw (18900 samples, 2025-10-21 to 2026-08-21).
//
// Measured out-of-sample: AUC 0.5187, accuracy 52.71%
// vs a 53.15% always-majority baseline. On calls it is
// confident enough to actually make, accuracy was 55.19% over
// 11.48% of samples. Regenerate with: npm run eval:predictor
import type { Model } from '@/services/predictor/model';

export const PRETRAINED: Model = {
  "version": 1,
  "weights": [
    -0.013074,
    -0.052619,
    -0.021074,
    -0.016461,
    -0.032679,
    0.026524,
    -0.030431,
    0.011091,
    0.077574,
    0.019183,
    0.022005,
    -0.008516,
    0.015525,
    -0.080657,
    -0.050217,
    -0.048955,
    -0.022111,
    0.055006,
    0.001857,
    0.053486,
    -0.003535,
    0.045105,
    0.03433,
    -0.044611,
    -0.037856,
    0.058123,
    0.12401,
    -0.111771
  ],
  "bias": 0.229677,
  "mean": [
    0.00067891,
    0.00337649,
    0.00668635,
    0.01293996,
    0.03607494,
    0.00370572,
    0.00650574,
    0.01214028,
    0.05724749,
    0.0000562,
    0.18037362,
    0.01792725,
    -0.06993506,
    0.02282885,
    0.0942779,
    -0.07480795,
    0.02126033,
    0.00036917,
    0.00002294,
    0.13370397,
    -0.1296997,
    0.23306557,
    0.00011893,
    0.01304697,
    0.03645409,
    0.05329721,
    0.01024965,
    -0.04356664
  ],
  "std": [
    0.02069476,
    0.04461413,
    0.06238003,
    0.08867575,
    0.15024864,
    0.03831999,
    0.04737196,
    0.07700747,
    0.34134983,
    0.00828508,
    1.29935234,
    0.01054359,
    0.37226149,
    0.01199592,
    0.5278222,
    0.0782925,
    0.1095361,
    0.00578364,
    0.0730052,
    0.37287215,
    0.12294706,
    1.03480946,
    0.12990201,
    0.05077271,
    0.07587267,
    0.06948582,
    0.00745492,
    0.05342007
  ],
  "samples": 152293,
  "trainedAt": 0
};

/** Out-of-sample measurements for the weights above, shown in the app. */
export const PRETRAINED_METRICS = {
  auc: 0.5187,
  accuracy: 0.5271,
  baselineAccuracy: 0.5315,
  confidentAccuracy: 0.5519,
  confidentCoverage: 0.1148,
  testSamples: 18900,
  holdoutMonths: 10,
};
